blank_issues_enabled: false
contact_links:
  - name: Community Discussions
    url: https://github.com/EtchDroid/EtchDroid/discussions
    about: For general questions, troubleshooting, or "How do I..." queries.
